export const PATH = {
    SIGN_IN: "users/signIn",
    SIGN_UP: "users/signUp",
    CATEGORIES: "categories",
    PRODUCTS: "products",
    PRODUCTS_ACTIVE:'products/active',
    PRODUCTS_BY_PARAMS:'products/filterValues',
    PRODUCTS_BY_CATEGORY: "products",
    PRODUCTS_FILTER:'products/filter',
    VENDORS_FILTER:'vendors/filter',
    UOM: 'products/uoms',
    WAREHOUSE: 'products/warehouses',
    ALL_WAREHOUSE: 'wareHouse/all',
    APPLICABLE_WAREHOUSE: 'wareHouse',
    VENDOR: 'vendors',
    VENODRS: 'vendors/vendors',
    VENDOR_CODE: 'vendors/vendorCode',
    ADDRESS: 'address',
    PINCODE: 'address/pinCode',
    PURCHASES: 'purchaseOrder',
    SALES: 'salesOrder',
    ISSUE: 'salesOrder/issue',
    TRANSFER:'transferOrders',
    PURCHASE_ORDER_BY_CODE:'purchaseOrder/poNumber',
    DRAFTTRANSFER:'transferOrders/draft',
    ONHAND_PARAMETERS:'onhand/ByParameters',
    ONHAND_DETAILED:'onhand/detailedOnhand',
    ONHAND_FIRSTLEVEL:'onhand/firstLevelOnHand',
    PURCHASE_CODE: 'purchaseOrder/purchaseOrderCode',
    SALES_ORDER_CODE:'salesOrder/salesOrderCode',
    TRANSFER_ORDER_CODE:'transferOrders/code',
    TRANSACTION: 'transaction',
    TRANSCODE: 'transaction/transactionCode',
    TRANSREASON : 'transaction/transactionReasons',
    DRAFTTRANS: 'transaction/draft',
    DRAFTSALES: 'salesOrder/draft',
    DRAFTPURCHASE:'purchaseOrder/draft',
    PRODUCTCODE: 'products/amulyaCode/',
    PURCHASE_RECEIVE:'purchaseOrder/receive',
    STATES:'address/states',
    CITIES:'address',
    LOT_NUMBERS:'onhand/lotNumbers',
    QTY_CHECK_PARAM:'purchaseOrder/qualityCheckParameters',
    COMPLETE_QC:'purchaseOrder/completeQC',
    SAVE_QC:'purchaseOrder/saveQualityCheck',
    DISTRIBUTOR:'distributor',
    DISTRIBUTOR_REG:'distributor/register',
    DISTRIBUTOR_UPDATE:'distributor/completeDetails',
    DISTRIBUTOR_NAME_UPDATE:'distributor/name',
    DISTRIBUTOR_FILTER:'distributor/filter',
    DISTRIBUTOR_KYC:'distributor/uploadKYC',
    DISTRIBUTOR_ID:'distributor',
    ACTIVE_DISTRIBUTOR:'distributor/active/',
    DISTSTATUS:'distributor/distributorStatuses',
    BANK:'bank',
};
  
  export const SERVER_PATHS = {
    // DEV:"https://amulya-api.el.r.appspot.com/api/v1/",
    DEV:"https://amulya-api-stag.el.r.appspot.com/api/v1/"
    // DEV: "http://3.95.36.75:8010/api/v1/"
  };
  